version: '3.8'

services:
  diplom-frontend:
    build:
      context: .
      target: production
      args:
        VITE_API_URL: ${VITE_API_URL}
    restart: always
    ports:
      - '80:80'
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.diplom-frontend.rule=Host(`diplom-test-qc0kmh-e8097e-176-109-107-66.traefik.me`)
      - traefik.http.routers.diplom-frontend.entrypoints=websecure
      - traefik.http.routers.diplom-frontend.tls.certResolver=letsencrypt
      - traefik.http.services.diplom-frontend.loadbalancer.server.port=80

networks:
  dokploy-network:
    external: true
